/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uea.voemais.client.view;

import com.uea.voemais.shared.flight.controller.FlightController;
import com.uea.voemais.shared.flight.model.Flight;
import java.util.List;

/**
 *
 * @author abatu
 */
public class ClientDataFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientDataFrame
     */
    public ClientDataFrame() {
        initComponents();
        
        this.destinationFinishComboBox.setVisible(false);
        this.destinationFinishLabel.setVisible(false);
        
        List<Flight> flightList = FlightController.getFromDB();
        
         for (Flight flight : flightList) {
             System.out.println("Flight: "+flight.getId());
            this.destinationStartComboBox.addItem(flight.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        destinationFinishLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        destinationStartComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        destinationFinishComboBox = new javax.swing.JComboBox<>();
        justDepartureRadioButton = new javax.swing.JRadioButton();
        departureAndArrivalRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton.setText("PRÓXIMO");
        jButton.setToolTipText("");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setText("VOLTAR");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        destinationFinishLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        destinationFinishLabel.setForeground(new java.awt.Color(255, 255, 255));
        destinationFinishLabel.setText("Destino de volta:");
        destinationFinishLabel.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Comprar Passagem: Selecionar destino");

        destinationStartComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                destinationStartComboBoxItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Destino de ida:");

        destinationFinishComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        justDepartureRadioButton.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(justDepartureRadioButton);
        justDepartureRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        justDepartureRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        justDepartureRadioButton.setSelected(true);
        justDepartureRadioButton.setText("Somente ida");
        justDepartureRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                justDepartureRadioButtonActionPerformed(evt);
            }
        });

        departureAndArrivalRadioButton.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(departureAndArrivalRadioButton);
        departureAndArrivalRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        departureAndArrivalRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        departureAndArrivalRadioButton.setText("Ida e volta");
        departureAndArrivalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureAndArrivalRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinationStartComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinationFinishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinationFinishComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(justDepartureRadioButton)
                        .addGap(32, 32, 32)
                        .addComponent(departureAndArrivalRadioButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationFinishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationStartComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationFinishComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(justDepartureRadioButton)
                    .addComponent(departureAndArrivalRadioButton))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        List<Flight> flightList = FlightController.getFromDB();
        Flight departureFlight = flightList.get(this.destinationStartComboBox.getSelectedIndex());
        
        Flight arrivalFlight = null;
        
        if(this.destinationFinishComboBox.isVisible()){
            flightList.remove(this.destinationStartComboBox.getSelectedIndex());
            arrivalFlight = flightList.get(this.destinationFinishComboBox.getSelectedIndex());
        }
        
        RegisterPassengersJFrame dados = new RegisterPassengersJFrame(departureFlight, arrivalFlight);
        dados.pack();
        dados.show();
        this.dispose();
    }//GEN-LAST:event_jButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        ClientMenuJFrame dados = new ClientMenuJFrame();

        dados.pack();
        dados.show();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void justDepartureRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_justDepartureRadioButtonActionPerformed
        this.destinationFinishComboBox.setVisible(false);
        this.destinationFinishComboBox.removeAllItems();
        this.destinationFinishLabel.setVisible(false);
    }//GEN-LAST:event_justDepartureRadioButtonActionPerformed

    private void departureAndArrivalRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureAndArrivalRadioButtonActionPerformed
        this.destinationFinishComboBox.setVisible(true);
        this.destinationFinishLabel.setVisible(true);
        
         List<Flight> flightList = FlightController.getFromDB();
         
         flightList.remove(this.destinationStartComboBox.getSelectedIndex());
         this.destinationFinishComboBox.removeAllItems();
        for (Flight flight : flightList) {
            this.destinationFinishComboBox.addItem(flight.toString());
        }
        
    }//GEN-LAST:event_departureAndArrivalRadioButtonActionPerformed

    private void destinationStartComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_destinationStartComboBoxItemStateChanged
         if(!this.destinationFinishComboBox.isVisible()&&!this.destinationFinishLabel.isVisible())return;
        
         List<Flight> flightList = FlightController.getFromDB();
         
         flightList.remove(this.destinationStartComboBox.getSelectedIndex());
         this.destinationFinishComboBox.removeAllItems();
        for (Flight flight : flightList) {
            this.destinationFinishComboBox.addItem(flight.toString());
        }
    }//GEN-LAST:event_destinationStartComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientDataFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton departureAndArrivalRadioButton;
    private javax.swing.JComboBox<String> destinationFinishComboBox;
    private javax.swing.JLabel destinationFinishLabel;
    private javax.swing.JComboBox<String> destinationStartComboBox;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton justDepartureRadioButton;
    // End of variables declaration//GEN-END:variables
}
